#:schema node_modules/wrangler/config-schema.json
account_id = ACCOUNT_ID
name = "blaze-cloudflare"
main = "debug.js"
compatibility_date = "2024-05-12"
workers_dev = true
# node_compat = true
routes = []
dev.port = 3000

logpush = true

[placement]
mode = "smart"